#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# Device Compatibilty
#/////////////////////////////////////////////////////////////////////////////////////

# Parameters
devcomp_device="$1"
devcomp_component="$2"
rootpath="INSTALLDIR"
legacy=false
pm_device=false

#/////////////////////////////////////////////////////////////////////////////////////
# Generic device settings
#/////////////////////////////////////////////////////////////////////////////////////

# Plus Generic
function generic_plus () {

	control_topic="$devcomp_device/command/$1"
	status_topic="$devcomp_device/status/$1"
	rpc_topic="$devcomp_device/rpc"
	status_out_topic="$devcomp_device/status/$1/out"
	status_command="status_update"
}

# Generic Switch
function generic_switch () {
	
	oncommand="on"
	offcommand="off"
	toggle_command="toggle"
}

# Generic Cover
function generic_cover () {

	oncommand="open"
	offcommand="close"
}

#/////////////////////////////////////////////////////////////////////////////////////
# Plus device settings
#/////////////////////////////////////////////////////////////////////////////////////

# Plus Switch
function plus_switch () {

	servicetemplate="$rootpath/service/shelly_plus.service"
	jsontemplate="$rootpath/template/shelly_plus_switch.json.template"
}

# Plus Cover
function plus_cover () {

	servicetemplate="$rootpath/service/shelly_plus.service"
	jsontemplate="$rootpath/template/shelly_plus_cover.json.template"
}

#/////////////////////////////////////////////////////////////////////////////////////
# Legacy device settings
#/////////////////////////////////////////////////////////////////////////////////////

# Legacy Switch
function legacy_switch () {

	control_topic="shellies/$devcomp_device/relay/0/command"
	status_topic="shellies/$devcomp_device/relay/0"
	servicetemplate="$rootpath/service/shelly_legacy.service"
	jsontemplate="$rootpath/template/legacy_switch.json.template"
	legacy=true
}

# Legacy Roller
function legacy_roller () {

	control_topic="shellies/$devcomp_device/roller/0/command"
	pos_control="shellies/$devcomp_device/roller/0/command/pos"
	pos_topic="shellies/$devcomp_device/roller/0/pos"
	power_topic="shellies/$devcomp_device/roller/0/power"
	energy_topic="shellies/$devcomp_device/roller/0/energy"
	servicetemplate="$rootpath/service/shelly_legacy.service"
	jsontemplate="$rootpath/template/legacy_roller.json.template"
	legacy=true
}

# Legacy Dimmer
function dimmer () {

	control_topic="shellies/$devcomp_device/light/0/command"
	status_topic="shellies/$devcomp_device/light/0/status"
	dim_value="shellies/$devcomp_device/light/0/set"
	power_topic="shellies/$devcomp_device/light/0/power"
	energy_topic="shellies/$devcomp_device/light/0/energy"
	servicetemplate="$rootpath/service/shelly_legacy.service"
	oncommand="on"
	offcommand="off"
	legacy=true
}

# Legacy Sensor
function sensor () {
	temperature_topic="shellies/$devcomp_device/sensor/temperature"
	humidity_topic="shellies/$devcomp_device/sensor/humidity"
	battery_topic="shellies/$devcomp_device/sensor/battery"
	servicetemplate="$rootpath/service/shelly_ht.service"
}

# Legacy PowerMeter
function legacy_pm () {

	energy_topic="shellies/$devcomp_device/relay/0/energy"
	power_topic="shellies/$devcomp_device/relay/0/power"
	temperature_topic="shellies/$devcomp_device/temperature"
	pm_device=true
}

#/////////////////////////////////////////////////////////////////////////////////////
# Multi-Purpose device settings
#/////////////////////////////////////////////////////////////////////////////////////

# ShellySwitch25 (Switch or Cover)
function legacy_switch25() {
    if [[ $devcomp_component == switch* ]]; then
		generic_switch
        legacy_switch
    elif [[ $devcomp_component == cover* || "$devcomp_devtype" == "roller" ]]; then
		generic_cover
        legacy_roller
    fi
}

# ShellyPlus2PM
plus_switch_cover() {
    if [[ $devcomp_component == switch* ]]; then
		generic_switch
		generic_plus "$devcomp_component"		
        plus_switch "$devcomp_component"
    elif [[ $devcomp_component == cover* ]]; then
		generic_cover
		generic_plus "$devcomp_component"
        plus_cover "$devcomp_component"
    fi
}

#/////////////////////////////////////////////////////////////////////////////////////
# Main
#/////////////////////////////////////////////////////////////////////////////////////

# Main
case $devcomp_device in
    shelly1-* | shelly1pm-*)
		generic_switch
        legacy_switch
        [[ "$devcomp_device" == shelly1pm-* ]] && legacy_pm
        ;;
    shellyswitch25-*)
        legacy_switch25
        ;;
    shellyplus1-* | shellyplus1pm-* | shelly1mini-* | shelly1pmmini-*)
		generic_plus "switch:0"
		generic_switch
        plus_switch "switch:0"
        [[ "$devcomp_device" == shellyplus1pm-* || "$devcomp_device" == shelly1pmmini-* ]] && pm_device=true
        ;;
    shellyplus2pm-*)
        plus_switch_cover
        pm_device=true
        ;;
    shellyht-*)
        sensor
        ;;
    *)
        statusmsg INPUT="ERROR" MSG="Gerät nicht kompatibel"
        exit 1
        ;;
esac
