#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# Device Compatibilty
#/////////////////////////////////////////////////////////////////////////////////////

# Parameters
devcomp_device="$1"
devcomp_component="$2"
rootpath="INSTALLDIR"
legacy=false
pm_device=false

# Legacy Switch
function legacy-switch () {

	control_topic="shellies/$devcomp_device/relay/0/command"
	status_topic="shellies/$devcomp_device/relay/0"
	oncommand="on"
	offcommand="off"
	toggle_command="toggle"
	servicetemplate="$rootpath/service/shelly_legacy.service"
	jsontemplate="$rootpath/template/legacy_switch.json.template"
	legacy=true
}

# Legacy PowerMeter
function legacy-pm () {

	energy_topic="shellies/$devcomp_device/relay/0/energy"
	power_topic="shellies/$devcomp_device/relay/0/power"
	temperature_topic="shellies/$devcomp_device/temperature"
	pm_device=true
}

# Plus Switch
function plus-switch () {

	control_topic="$devcomp_device/command/$1"
	status_topic="$devcomp_device/status/$1"
	rpc_topic="$devcomp_device/rpc"
	status_out_topic="$devcomp_device/status/$1/out"
	status_command="status_update"
	oncommand="on"
	offcommand="off"
	toggle_command="toggle"
	servicetemplate="$rootpath/service/shelly_plus.service"
	jsontemplate="$rootpath/template/shelly_plus_switch.json.template"
}

# Plus Cover
function plus-cover () {

	control_topic="$devcomp_device/command/$1"
	status_topic="$devcomp_device/status/$1"
	rpc_topic=s"$devcomp_device/rpc"
	status_out_topic="$devcomp_device/status/$1/out"
	status_command="status_update"
	oncommand="open"
	offcommand="close"
	servicetemplate="$rootpath/service/shelly_plus.service"
	jsontemplate="$rootpath/template/shelly_plus_cover.json.template"
}

# Legacy Roller
function legacy-roller () {

	control_topic="shellies/$devcomp_device/roller/0/command"
	pos_control="shellies/$devcomp_device/roller/0/command/pos"
	pos_topic="shellies/$devcomp_device/roller/0/pos"
	power_topic="shellies/$devcomp_device/roller/0/power"
	energy_topic="shellies/$devcomp_device/roller/0/energy"
	oncommand="open"
	offcommand="close"
	servicetemplate="$rootpath/service/shelly_legacy.service"
	jsontemplate="$rootpath/template/legacy_roller.json.template"
	legacy=true
}

# Legacy Dimmer
function dimmer () {

	control_topic="shellies/$devcomp_device/light/0/command"
	status_topic="shellies/$devcomp_device/light/0/status"
	dim_value="shellies/$devcomp_device/light/0/set"
	power_topic="shellies/$devcomp_device/light/0/power"
	energy_topic="shellies/$devcomp_device/light/0/energy"
	servicetemplate="$rootpath/service/shelly_legacy.service"
	oncommand="on"
	offcommand="off"
	legacy=true
}

# Legacy Switch
function sensor () {
	temperature_topic="shellies/$devcomp_device/sensor/temperature"
	humidity_topic="shellies/$devcomp_device/sensor/humidity"
	battery_topic="shellies/$devcomp_device/sensor/battery"
	servicetemplate="$rootpath/service/shelly_ht.service"
}

# Main
if [[ $devcomp_device == shelly1-* ]]; then

	legacy-switch

elif [[ $devcomp_device == shelly1pm-* ]]; then

	legacy-switch
	legacy-pm

elif [[ $devcomp_device == shellyswitch25- ]]; then
	
	if [[ $devcomp_component == switch* ]]; then 

		legacy-switch
	
	elif [[ $devcomp_component == cover* ]]; then 
	
		legacy-roller
		
	elif [ "$devcomp_devtype" = "roller" ]; then 
	
		legacy-roller
	
	fi

elif [[ $devcomp_device == shellyplus1-* ]]; then
	
	plus-switch "switch:0"

elif [[ $devcomp_device == shellyplus1pm-* ]]; then
	
	plus-switch "switch:0"
	pm_device=true

elif [[ $devcomp_device == shelly1mini-* ]]; then
	
	plus-switch "switch:0"

elif [[ $devcomp_device == shelly1pmmini-* ]]; then
	
	plus-switch "switch:0"
	pm_device=true

elif [[ $devcomp_device == shellyplus2pm-* ]]; then
	
	if [[ $devcomp_component == switch* ]]; then
		plus-switch $devcomp_component
	fi

	if [[ $devcomp_component == cover* ]]; then
		plus-cover $devcomp_component
	fi
	
	pm_device=true

elif [[ $devcomp_device == shellyht-* ]]; then
	
	sensor

else

	statusmsg INPUT="ERROR" MSG="Gerät nicht kompatibel"
	exit 1

fi
