#!/bin/bash
#/////////////////////////////////////////////////////////////////////////////////////
# Shelly MQTT Status 
#/////////////////////////////////////////////////////////////////////////////////////

# Catch parameters
device="$1"

# Load config
source /opt/nanohome/config.cfg

# Device Support
source $rootpath/devcompatibility $device

# Main
while read rpc; do

	now=$(date +"%T")

	# parse rpc-json
	energy=$(echo $rpc | jq -r .aenergy.total )
	power=$(echo $rpc | jq -r .apower )
	voltage=$(echo $rpc | jq -r .voltage )
	current=$(echo $rpc | jq -r .current )
	temperature=$(echo $rpc | jq -r .temperature.tC )
	output=$(echo $rpc | jq -r .output )
	status=0
	statustxt="Off"
	if $output; then status=1; statustxt="On"; fi
	
	echo "---------------------------------"
	echo "Device: $device"
	echo "Description: $devdescription"
	echo "Status: $status"
	echo "Energy: $energy Wh"
	echo "Power: $power W"
	echo "Voltage: $voltage V"
	echo "Current: $current A"
	echo "Temperature: $temperature °C"
	echo "---------------------------------"
	
	# insert values into influxdb
	curl -i -XPOST "http://$influxdb_server:8086/write?db=$influxdb_database" --data-binary "$devdescription Status=$status"
	curl -i -XPOST "http://$influxdb_server:8086/write?db=$influxdb_database" --data-binary "$devdescription Energy=$energy"
	curl -i -XPOST "http://$influxdb_server:8086/write?db=$influxdb_database" --data-binary "$devdescription Power=$power"
	curl -i -XPOST "http://$influxdb_server:8086/write?db=$influxdb_database" --data-binary "$devdescription Voltage=$voltage"
	curl -i -XPOST "http://$influxdb_server:8086/write?db=$influxdb_database" --data-binary "$devdescription Current=$current"
	curl -i -XPOST "http://$influxdb_server:8086/write?db=$influxdb_database" --data-binary "$devdescription Temperature=$temperature"
	
	# Send status to mqtt topic
	mosquitto_pub -h $mqtt_server -u $mqtt_system_user -P $mqtt_system_pass -t $status_out_topic -m $statustxt

done < <(mosquitto_sub -h $mqtt_server -u $mqtt_system_user -P $mqtt_system_pass -t $status_topic -q 2)